### ISSUE TITLE
[Об измерении сложности Друпала]: 

### ISSUE THREAD

**Issue by Anykey1994** [Druki-ru/content#103]
### Описание

Насколько именно сложен Друпал? Как новичку понять - совладает он с ним до необходимого ему уровня за приемлемое время, или только впустую потратит время (и уйдёт врагом сообщества, которое не предупредило его о ТАКИХ сложностях)? Смешная картинка "Кривая вхождения в Друпал" - она про сам Друпал или про уже неотъемлемые от него части (Docker, Composer, Twig и т.д.)? 
К  примеру, Алиса изначально собирается профессионально изучать веб-разработку и лучше Друпала для него ничего нет (или мало что есть). А Боб пришёл чисто себе "сайтик запилить", причём хочется сайтик добротный, но всё же ценой разумных затрат сил и времени, по соотношению "затраты/результат". Как Бобу понять, именно в его случае где проходит грань "разумных затрат"? Вот, скажем, месяц он готов ничего не делать (так это выглядит для окружающих и, возможно, для него самого) и изучать Друпал; ну полтора; но через три у него уже точно дедлайн, а ещё ж собственно сайт нужно наполнить и всякое там допилить, на что потребуется, скажем, месяц времени, и выходит, что больше двух месяцев вот совсем нет возможности учить. Да, "тебе никто ничего не обещал" и "всё индивидуально", но... вот бы человеколюбия бы сюда кусочек.

Заявляется, с одной стороны, "програмирование знать не требуется", с другой - боль и кровь из глаз могут случиться даже на этапе ввода паролей в settings.php, когда сайт даже вроде бы взлетел, но доступа к БД нету, т.к. ответственный юзер воспользовался менеджером паролей и сгенерировал отличный пароль со спецсимволами, но при вводе его в settings.php движок опознал окончание пароля в одном месте (внезапно это ' ), а юзер его из менеджера паролей вводит целиком и он, понятно, не принимается. Вот сам лично дважды наступал на эти грабли - и один ли я? И сделать об этом предупреждение хотя бы в документации "нет смысла, поскольку, если ты не умеешь в PHP, ты не играешь в Друпал, и/или иди и изучай PHP" - и получается, что человек пришёл в Друпал, а его отправляют прежде учить PHP.

Итак, с оценкой (хотя бы объективной) сложности Друпала - неясность, которую предлагаю прояснить.

### Желаете написать его?

Да

**Comment by Niklan** [comment]
В FaQ же вроде есть ответ на данный вопрос https://druki.ru/wiki/faq#ya-polnyy-novichok-v-veb-razrabotkedrupal-stoit-li-mne-ispolzovat-drupal

> Drupal нацелен на относительно опытных пользователей

Да, им можно без кода достаточно далеко уйти и сделать сложные сайты, но потребность в коде всё равно прижмёт к стене рано или поздно, если заниматься им не на любительском уровне и вот тут врата ада открываются, ибо погружаться придётся серьезно. Херак-херак и в продакшн тут не работает, либо прилетит ответкой в будущем.

**Comment by Niklan** [comment]
Закрываю данный ишью в связи с отсутствием активности и каких-то задач, требующих решение. Если остались вопросы, или он еще актуален, можно открыть обратно.
