### ISSUE TITLE
Обратная связь: Сервисы

### ISSUE THREAD

**Issue by Hesychast** [Druki-ru/content#121]
С самого начала "По своей сути, сервисы, это самые обычные PHP объекты"  и дальше по тексту объекты, объекты, объекты... Объект - это экземпляр класса. Конструктор у класса, а не у объекта. Объекты не регистрируются в виде сервиса, только классы. 

Необходимо заменить в тексте объект на класс. 

Вот когда идет обращение к сервису, тогда как раз создается объект, т.е. экземпляр класса, зарегистрированного в сервисе.

---

- **Entity ID:** 2420
- **Slug:** wiki/8/services
- **Core (if set):** 8
- **Relative pathname:** docs/ru/drupal/8/services/index.md

**Comment by chesn0k** [comment]
Спорное утверждение
https://symfony.com/doc/current/service_container.html

**Comment by Hesychast** [comment]
Например, вот цитата из руководства на которое вы мне оставили ссылку: "When you ask for the MessageGenerator service, the container constructs a new MessageGenerator object..." Вдумайтесь о чем там идет речь, посмотрите код. MessageGenerator - это класс, а сервис контейнер при обращнии создает экземпляр MessageGenerator, т. е. объект. Если вы не видите этом разницы, значит вы не до конца понимаете ООП. Либо, если захотите сослаться на первые два абзаца этого же руководства, вы не слишком правильно смогли их перевести. 
`Your application is full of useful objects: a "Mailer" object might help you send emails while another object might help you save things to the database. Almost everything that your app "does" is actually done by one of these objects. And each time you install a new bundle, you get access to even more!

In Symfony, these useful objects are called services and each service lives inside a very special object called the service container. The container allows you to centralize the way objects are constructed. It makes your life easier, promotes a strong architecture and is super fast!`

Тут речь идет о приложении существующем в настоящем, сиюминутном времени, а стало быть сервис контейнер уже насоздавал экземпляров классов, т.е. объектов.

**Comment by Hesychast** [comment]
Например, вот цитата из руководства на которое вы мне оставили ссылку: "When you ask for the MessageGenerator service, the container constructs a new MessageGenerator object..." Вдумайтесь о чем там идет речь, посмотрите код. MessageGenerator - это класс, а сервис контейнер при обращнии создает экземпляр MessageGenerator, т. е. объект. Если вы не видите этом разницы, значит вы не до конца понимаете ООП. Либо, если захотите сослаться на первые два абзаца этого же руководства, вы не слишком правильно смогли их перевести. Вот они:

_Your application is full of useful objects: a "Mailer" object might help you send emails while another object might help you save things to the database. Almost everything that your app "does" is actually done by one of these objects. And each time you install a new bundle, you get access to even more!_

_In Symfony, these useful objects are called services and each service lives inside a very special object called the service container. The container allows you to centralize the way objects are constructed. It makes your life easier, promotes a strong architecture and is super fast!_

Тут речь идет о приложении существующем в настоящем, сиюминутном времени, а стало быть сервис контейнер уже насоздавал экземпляров классов, т.е. объектов.

**Comment by Hesychast** [comment]
Например, вот цитата из руководства на которое вы мне оставили ссылку: "When you ask for the MessageGenerator service, the container constructs a new MessageGenerator object..." Вдумайтесь о чем там идет речь, посмотрите код. MessageGenerator - это класс, а сервис контейнер при обращнии создает экземпляр MessageGenerator, т. е. объект. Если вы не видите этом разницы, значит вы не до конца понимаете ООП.
