### ISSUE TITLE
Обновить скриншоты установки до Drupal 9

### ISSUE THREAD

**Issue by Niklan** [Druki-ru/content#13]
https://github.com/Druki-ru/content/blob/master/docs/ru/9/installation.md

Тут скрины из Drupal 8, нужны аналогичные с 9 ки.

**Comment by a-kovrigin** [comment]
#21 Добавил варианты скриншотов для 9.0.6, но они сделаны под win.
Не уверен, подойдёт ли в плане единообразия.

**Comment by Niklan** [comment]
@a-kovrigin привет, у тебя остались скрины? Я не обратил внимания, ты загрузил скрины на ibb.co а не imgur, они протухли, и пропали с сайта.

**Comment by a-kovrigin** [comment]
@Niklan дропнул их недавно :(

**Comment by Niklan** [comment]
Не страшно) Завтра тогда с сервера вытащу, должны были остаться, сбой был и они должны были сохраниться.
