### ISSUE TITLE
Добавить навигацию вперед/назад на странице релиза

### ISSUE THREAD

**Issue by DimaSuharchuk** [Druki-ru/content#148]
Было бы неплохо добавить навигацию на страницах релизов вверху и внизу страницы. 

Например, я нахожусь на странице релиза 9.3.0, и есть стрелочка на предыдущую версию (9.2.11) и на следующую, если существует (9.3.1).

Как это могло бы выглядеть, либо обе стрелочки справа страницы.
![image](https://user-images.githubusercontent.com/28755415/152542293-41b403b2-e91d-48a8-b0ea-fd6edf94c92d.png)

**Comment by Niklan** [comment]
Перенёс это в репозиторий содержимого, так как для начала это стоит попробовать сделать на имеющемся функционале категоризации. Категоризировать релизы по минорной версии и кнопочки появятся, и список.

**Comment by Niklan** [comment]
Всем релизам добавлена соответствующая навигация:

![image](https://user-images.githubusercontent.com/2356744/152645300-2bc7cadb-c54a-4189-8f86-bb5d99f60eb8.png)

Спасибо за полезную идею, действительно удобнее для всех.
