### ISSUE TITLE
Обратная связь: Drupal мероприятия

### ISSUE THREAD

**Issue by konqueror7** [Druki-ru/content#38]
Опишите, что не так.
https://druki.ru/wiki/events#treningi
Раздел "Тренинги"
Второй абзац:
"Подобные мероприятия **имеются** отличный формат. "
Лучше изложить так:
"Подобные мероприятия являются отличным форматом"
---

- **Entity ID:** 133
- **External ID:** events
- **Core (if set):** 
- **Relative pathname:** docs/ru/drupal/events/events.md
- **Sync timestamp:** 1603082403

**Comment by Niklan** [comment]
Спасибо!
