### ISSUE TITLE
Обратная связь: Создание хуков

### ISSUE THREAD

**Issue by konqueror7** [Druki-ru/content#53]
Опишите, что не так.

> "У хуков нет централизованного хранилища или менеджера поэтому их вызов и обработку может находиться абсолютно где угодно."

Лучше будет так:

> "У хуков нет централизованного хранилища или менеджера, поэтому произвести их вызов и обработку можно из любого модуля или функции в коде Drupal."

---

- **Entity ID:** 508
- **External ID:** create-hook
- **Core (if set):** 8
- **Relative pathname:** docs/ru/drupal/8/hooks/create-hook.md
- **Sync timestamp:** 1613565675

**Comment by Niklan** [comment]
Нужно обновить для [Drupal 8](https://github.com/Druki-ru/content/blob/master/docs/ru/drupal/8/hooks/create-hook.md) и [Drupal 9](https://github.com/Druki-ru/content/blob/master/docs/ru/drupal/9/hooks/hooks.md).

**Comment by chesn0k** [comment]
Я исправлю

**Comment by batkor** [comment]
Наверное правильно будет вот так
"У хуков нет централизованного хранилища или менеджера, поэтому произвести их вызов и обработку можно из любого модуля или темы."

**Comment by Niklan** [comment]
> Наверное правильно будет вот так
> "У хуков нет централизованного хранилища или менеджера, поэтому произвести их вызов и обработку можно из любого модуля или темы."

Я не считаю что тут стоит упоминать тему. Хоть это и возможно, но это очень редкие кейсы, на сколько я знаю, такое не практикуется. Разве что базовыми темами.

В общем, такое упоминание должно быть добавлено очень аккуратно, ибо, например, в WordPress, практикуется писать весь код прямо в темах, и если у разработчика есть такой опыт, он с большой вероятностью начнёт описывать хуки в теме, что скорее всего, будет просто плохой практикой и приведёт к проблемам в будущем.

Возможно стоит закончить более техническим термином, всё равно тот, кто описывает свои хуки, подразумевается что разработчик. А именно, что-то типа:

> У хуков нет централизованного хранилища или менеджера, произвести их вызов и обработку можно в коде, где есть доступ к контейнеру сервисов.

И линкануть на сервисы в добавок. Ведь по сути, вызов хука допустим везде, где есть возможность дёрнуть `module_handler` и `theme_handler` сервисы, а они доступны везде где доступен контейнер сервисов.

**Comment by Niklan** [comment]
Или вовсе переформулировать абзац:

> Вызов хуков производится при помощи сервисов `module_handler` - для реализаций в модулях и `theme_handler` - для реализаций в темах оформления.

*Нужно уточнить как точно называться сервис theme_handler.*

**Comment by SemanticsPRO** [comment]
> Я не считаю что тут стоит упоминать тему. Хоть это и возможно, но это очень редкие кейсы, на сколько я знаю, такое не практикуется. Разве что базовыми темами.
Согласен, не стоит вскрывать эту тему. Вы молодые, шутливые, вам все легко. Это не то.

Мне кажется, что акцентировать внимание на хранилище вообще бессмысленно.
Нужно прививать хорошие правила, что хуки относящие к скоупу данных пишите в .module, к скопу темизации - в теме.
Всё

**Comment by Niklan** [comment]
> > Я не считаю что тут стоит упоминать тему. Хоть это и возможно, но это очень редкие кейсы, на сколько я знаю, такое не практикуется. Разве что базовыми темами.
> 
> Согласен, не стоит вскрывать эту тему. Вы молодые, шутливые, вам все легко. Это не то.
> 
> Мне кажется, что акцентировать внимание на хранилище вообще бессмысленно.
> Нужно прививать хорошие правила, что хуки относящие к скоупу данных пишите в .module, к скопу темизации - в теме.
> Всё

Это исправление в контексте "объявления своих хуков", то есть для тех, кто хочет свои хуки создать. То есть, по большей части про вызов `module_handler->invokeAll()` и т.д.

**Comment by Niklan** [comment]
К слову, в этом материале не указано что хуки для тем вызываются `theme_handler` и что хуки для модулей и тем не одно и тоже.

Надо новый ишью под это сделать и дописать.

**Comment by Niklan** [comment]
В общем, думаю в текущей версии, текущий вариант звучит нормально.

Я продолжу в #55.

**Comment by konqueror7** [comment]
> В общем, думаю в текущей версии, текущий вариант звучит нормально.
> 
> Я продолжу в #55.



> В общем, думаю в текущей версии, текущий вариант звучит нормально.

Вам виднее, только запятую перед "поэтому" и глагол "произвести" все равно добавьте. И формулировка "абсолютно где угодно" - очень широкая, неужели и в поле body ноды тоже можно хук вставить? Случаи стоило бы указать.

**Comment by chesn0k** [comment]
@konqueror7 под словом "текущий" имеется ввиду вариант предложенный вами.

**Comment by konqueror7** [comment]
> @konqueror7 под словом "текущей" имеется ввиду вариант предложенный вами.

А-а-а, понял! Тогда извините, пошел дальше изучать энциклопедию.
