### ISSUE TITLE
Дополнить как вызываются хуки объявленные в темах

### ISSUE THREAD

**Issue by Niklan** [Druki-ru/content#55]
К слову, в этом материале не указано что хуки для тем вызываются `theme_handler` и что хуки для модулей и тем не одно и тоже.

Надо новый ишью под это сделать и дописать.

_Originally posted by @Niklan in https://github.com/Druki-ru/content/issues/53#issuecomment-782592589_

**Comment by Niklan** [comment]
Надо уточнить как вызываются хуки из тем. Вроде там раньше был отдельный вызов для них. `them_handler` не имеет этого вызова. Возможно объединили, стоит уточнить и поправить если такое разделение осталось.

**Comment by batkor** [comment]
Для модуля https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21ModuleHandler.php/class/ModuleHandler/9.1.x
Для темы
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Theme%21ThemeManager.php/class/ThemeManager/9.1.x

**Comment by Niklan** [comment]
@batkor ThemeManager содержит только вызов альтер хуков для темы. Но у тем работают и обычные хуки. Насколько я помню не все, то есть для обычных хуков там вроде как свой отдельный механизм, и он очевидно не в theme manager.

**Comment by Niklan** [comment]
По всей видимости (нужно проверить):
- Исполняемые хуки доступны только модулям. За исключением "хуков" вызываемых ThemeManager / ThemeRegistry таких, как `hook_theme()`, `hook_preprocess_HOOK()`.
- Альтер хуки доступны и модулям и темам, но вызываются они своими ответственными сервисами `module_handler->alter()`, `theme_handler->alter()`.
