### ISSUE TITLE
Обратная связь: settings.php — настройки окружения сайта

### ISSUE THREAD

**Issue by Anykey1994** [Druki-ru/content#81]
Опишите, что не так.
Вот здесь https://druki.ru/wiki/9/settings-php#zagruzchik-klassov пишется:
"Вы также можете задекорировать базовый загрузчик с любым другим решением,"  - задекорировать? 

---

- **Entity ID:** 1232
- **Slug:** 9/settings-php
- **Core (if set):** 9
- **Relative pathname:** docs/ru/drupal/9/settings-php/index.md
- **Sync timestamp:** 1625746088

**Comment by Niklan** [comment]
@Anykey1994 да, https://refactoring.guru/ru/design-patterns/decorator/php/example

**Comment by Niklan** [comment]
Закрываю данный ишью в связи с отсутствием активности и каких-то задач, требующих действий и решений. Если остались вопросы, или он еще актуален, можно открыть обратно.
