### ISSUE TITLE
Обратная связь: settings.php — TTL кеша для ответов 4xx

### ISSUE THREAD

**Issue by Anykey1994** [Druki-ru/content#82]
"Элементы кеша которые хранятся на основе URL приводят к увеличению общего числа кеш элементов."  https://druki.ru/wiki/9/settings-php#ttl-kesha-dlya-otvetov-4xx - "на основе URL" -- здесь правильно сформулировано? Не "на основном URL"? А то подозрительно звучит.

Там же: 
"Для данных страницы вы можете задать свой собственный TTL "  - "для данных страниц" ?

---

- **Entity ID:** 1232
- **Slug:** 9/settings-php
- **Core (if set):** 9
- **Relative pathname:** docs/ru/drupal/9/settings-php/index.md
- **Sync timestamp:** 1625746088

**Comment by Niklan** [comment]
>  "на основе URL" -- здесь правильно сформулировано? Не "на основном URL"? А то подозрительно звучит.

Да, на основе URL. У /foo и /bar будет разный кеш "на основе URL", это кеш-контексты.

В оригинале это звучит так:

> Items cached per-URL tend to result in a large number of cache items, and this can be problematic on 404 pages which by their nature are unbounded. A fixed TTL can be set for these items, defaulting to one hour, so that cache backends which do not support LRU can purge older entries. To disable caching of client error responses set the value to 0. Currently applies only to page_cache module.

Может можно лучше перевести.

> "Для данных страницы вы можете задать свой собственный TTL " - "для данных страниц" ?

Да, опечатка.

**Comment by Anykey1994** [comment]
Элементы кеша которые хранятся на основе URL приводят к увеличению общего числа кеш элементов. Данное поведение может стать проблемой на 404 страницах, которых может быть очень много. Для данных страницы вы можете задать свой собственный TTL (Time To Live) в секундах. По умолчанию это значение равняется одному часу (3600 секунд). Для того чтобы отключить кеширование 4хх ответов, нужно задать значение 0.
