### ISSUE TITLE
Обратная связь: settings.php — настройки окружения сайта

### ISSUE THREAD

**Issue by Anykey1994** [Druki-ru/content#83]
https://druki.ru/wiki/9/settings-php#razreshenie-avtorizovannykh-operaciy
"На серверах с дополнительной защитой менеджер обновлений потребует предоставить доступы для SSH или FTP прежде чем операция будет выполнена."
&mdash; будет ли корректно вот так:
"На серверах с дополнительной защитой менеджер обновлений потребует предъявить права на доступ по протоколам SSH или FTP перед тем, как начать." ?

---

- **Entity ID:** 1232
- **Slug:** 9/settings-php
- **Core (if set):** 9
- **Relative pathname:** docs/ru/drupal/9/settings-php/index.md
- **Sync timestamp:** 1625746088

**Comment by Niklan** [comment]
Да, звучит корректно.

**Comment by batkor** [comment]
Оригинальный текст
```php
* The Update Manager module included with Drupal provides a mechanism for
 * site administrators to securely install missing updates for the site
 * directly through the web user interface. On securely-configured servers,
 * the Update manager will require the administrator to provide SSH or FTP
 * credentials before allowing the installation to proceed; this allows the
 * site to update the new files as the user who owns all the Drupal files,
 * instead of as the user the webserver is running as.
```

думаю лучше оставить как есть, а именно "предоставить"

**Comment by Anykey1994** [comment]
"Предоставлять" - больше про обеспечение доступа к к-л ресурсам или возможностям, а аусвайс требуется именно "предъявить". Ну, "представить".

**Comment by Niklan** [comment]
Закрываю данный ишью в связи с отсутствием активности и каких-то задач, требующих действий и решений. Если остались вопросы, или он еще актуален, можно открыть обратно.
