### ISSUE TITLE
settings.php — соль

### ISSUE THREAD

**Issue by Anykey1994** [Druki-ru/content#87]
Опишите, что не так.
Вот раздел https://druki.ru/wiki/9/settings-php#sol
Сейчас сформулировано:
"Для более продвинутой защиты вы можете вынести значение соли за пределы Drupal и запрашивать его из файла или иных мест."

Вот когда говорится "за пределы Друпал... иных мест" - это как-то очень куцо получается. ЧтО имеется в виду под "Друпал"? Я вот полазил по каталогам на хостинге и мне не открылось, как это правильно сформулировать. Пока пишу, что "за пределами каталога www на хостинге".

Сейчас получается, что "За пределы Друпал" значит и "за пределы каталога www на хостинге, но внутри того же хоста (на локалке или на сервере)" и, одновременно,  "за пределы данного хоста".

Давайте распишем чуток подробнее, а то для кого-то может оказаться непонятно и он полезет искать уточнений; а это будет означать, что druki не даёт исчерпывающих объяснений (а вроде бы должен).

Опять же, это вопрос безопасности, поэтому тут хорошо будет или дать краткую инструкцию, куда конкретно ложить оную соль, или/и отослать к некоей расширенной инструкции.

Сейчас предлагаю такой вариант: "Для более продвинутой защиты вы можете вынести значение соли за пределы Drupal (т.е. разместить соль как в пределах данного хостинга, но вне каталога www; так и где-либо в интернете) и указать Друпалу запрашивать его оттуда."

---
- **Entity ID:** 1232
- **Slug:** 9/settings-php
- **Core (if set):** 9
- **Relative pathname:** docs/ru/drupal/9/settings-php/index.md
- **Sync timestamp:** 1627663392

**Comment by Niklan** [comment]
> Вот когда говорится "за пределы Друпал... иных мест" - это как-то очень куцо получается. 

Подразумевается проект.

> Сейчас получается, что "За пределы Друпал" значит и "за пределы каталога www на хостинге, но внутри того же хоста (на локалке или на сервере)" и, одновременно, "за пределы данного хоста".

Вот эта часть еще более запутанная «за пределы каталога www на хостинге» — не ясно что такое каталог www. Это уже какие-то частные случаи. Есть термины Project Root, Docroot и вот «пределы Drupal» — это как раз Project Root.

Соль может быть вообще где угодно, до тех пор, пока разработчик может получить доступ к этому значению при помощи PHP.

> Дать краткую инструкцию, куда конкретно ложить оную соль, или/и отослать к некоей расширенной инструкции.

Там представлен пример как можно соль получать из файла. По умолчанию, соль там хранится как строка. Нет смысла особо давать другие варианты. Даже стандартный со строкой более чем безопасный, так как доступа к файлу нет ни у кого кроме веб-сервера. Как правило, соль выносят из строки в определённых окружениях, особенно когда продакшен на докерах. Но кто такие проекты поднимает, уже разберутся сами что к чему, им такие уточнения точно не потребуются.

Пример считаю отличным, это официальный пример. Больше и не надо. Тем более, по умолчанию, как я уже написал, соль будет строкой и этого хватит 99%+ проектам и не будет представлять никаких проблем и угроз.

Единственное, что там важно, но это относится не только к соли, а ко всему файлу **settings.php** — данные из файла должны быть надежно защищены. Например, вот это уже опасно: https://gitlab.com/drupal.ru/next/-/blob/dced852256f0246be22689fe500c9dd5433f5577/web/sites/default/settings.php#L283

**Comment by Niklan** [comment]
Закрываю данный ишью в связи с отсутствием активности и каких-то задач, требующих действий и решений. Если остались вопросы, или он еще актуален, можно открыть обратно.
