### ISSUE TITLE
«Кэш» или «Кеш»

### ISSUE THREAD

**Issue by Anykey1994** [Druki-ru/content#88]
Либо киньте в меня тапок за буквоедство, либо давайте определимся.

Как писать: "кэш" или "кеш"? 
Слово заимствованное, притом недавно, поэтому однозначно устоявшегося способа нет.
Авторитетным считается источник [gramota.ru](http://new.gramota.ru/gramota/about), но там противоречие: с одной стороны, [редакторы утверждают](http://new.gramota.ru/spravka/buro/search-answer?s=%D0%9A%D0%AD%D0%A8&start=0) "кеш", 
с другой стороны, Большой толковый словарь [утверждает](http://gramota.ru/slovari/dic/?bts=x&word=%D0%BA%D1%8D%D1%88) "кэш".

Мнение экспертов (или "экспертов", кто ж их там разберёт?) на bolshoyvopros.ru [неоднозначно, но вроде бы склоняется](http://www.bolshoyvopros.ru/questions/211611-kak-pravilno-kesh-ili-kesh-naprimer-kesh-kesh-brauzera.html)  к "кэш".

Так что выбор (традиции употребления данного слова) как бы за нами. И его лучше сделать просто для унификации оформления текста.

Человеку с испорченным изучением английского языка слухом "кеш" режет и слух, и взгляд. 

Посему предлагаю таки "кэш".

---

- **Entity ID:** 1232
- **Slug:** 9/settings-php
- **Core (if set):** 9
- **Relative pathname:** docs/ru/drupal/9/settings-php/index.md
- **Sync timestamp:** 1627663392

**Comment by Niklan** [comment]
> Как писать: "кэш" или "кеш"?

Кеш. У нас есть [Глоссарий](https://github.com/Druki-ru/content/blob/master/CONTRIBUTING.md#%D0%B3%D0%BB%D0%BE%D1%81%D1%81%D0%B0%D1%80%D0%B8%D0%B9). Я тоже долго изучал этот вопрос и таки, судя по всему, правильно - кеш. 

По вашей же ссылке:

> Правильно: кеш. Колебания в написании недавно заимствованных слов и неодинаковая их фиксация в разных словарях (или разных изданиях одного и того же словаря) – вещь вполне естественная: слово осваивается в языке. В спорных случаях **лучше придерживаться рекомендаций орфографического словаря**.

Тут также множество других примеров. Мы пишем плЕер, компьютЕр и т.д.

Так как ситуация двоякая, пишут по одному, а правильно по другому, думаю надо оставить этот ишью и проголосовать.

Пока что оставим орфографически правильное написание - кеш. В будущем, если что поменяем везде.

Я пока оставлю ишью висеть и пособираем различные мнения.

**Comment by Niklan** [comment]
В этом комменте, давайте **в реакциях** "проголосуем" как должно быть.

- 👍 - Кэш
- 👎 - Кеш

**Comment by Niklan** [comment]
Пока оставляем "Кеш", так как, на данный момент проголосовало:

- 1 за Кэш
- 4 за Кеш

Различные грамматические ресурсы также указывают на Кеш.
